excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sarcasm-kanimas.github.io
title: Nerdy Jumping
tagline: I'm not insane. My mom had me tested.
description: A sweet cake of fangirling on comics, movies, VIPs and TV series.
paginate: 5